apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kiln.fullname" . }}
  labels:
    {{- include "kiln.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
