apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kiln.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kiln.labels" . | nindent 4 }}
automountServiceAccountToken: false
